### ISSUE TITLE
Proposed Text Content

### ISSUE THREAD

**Issue by bradreeder** [saferTogether/saferTogether#35]
I've just written up the first draft of the text content for the landing and results pages. They can be found under the tab above labelled 'Wiki.'

If anyone could approve that they are happy with this content, or suggest any changes to it here it would be appreciated. :)

**Comment by shigufta-khan** [comment]
I have just had a look at the content on the landing page and the results page and think its good, concise and easy to read. Covers all the necessary information needed.

**Comment by Nicky-Cummings** [comment]
I agree, just read it and it reads really well. Thank you Bradley it can be hard to interpret what we need to achieve but you've done a great job. I'll call everyone and get their input asap.

Also, I prefer the idea of linking to the documents and saving space so I'll discuss this idea too. What do you think Shigufta?

**Comment by shigufta-khan** [comment]
Hi Nikki

Linking to the documents is a good idea, also Bradley number for Blackburn & Darwen District without abuse is 01254 260465 not sure what the other number is that’s next to our name.



[cid:image002.png@01CF9C2D.898D6480]Shigufta Khan | Chief Executive Officer
Blackburn & Darwen District
Without Abuse
43 King Street, Blackburn, BB2 2DH
Tel: 01254 260465

[cid:image005.png@01CF99C5.2F71FC00]Web: www.bddwa.org.uk<http://www.bddwa.org.uk/>
Email: shigufta.khan@bddwa.org.uk<mailto:shigufta.khan@bddwa.org.uk>


Supported by Comic Relief, Henry Smith and Children In Need. BDDWA is a registered charity and exists to assist in the relief of people who have suffered or who are at risk of suffering domestic abuse, through the provision of support, advice and accommodation.

[safer together logo (2)][cid:image001.png@01CF6197.DA126BB0][cid:image004.png@01CF6198.067B2250]

Registered company 5834929 Registered charity 1116444.

**Comment by Nicky-Cummings** [comment]
Great, Amanda is reviewing now too and just spoken to Jen.

Re the safety resources we agreed also that the links rather than copy would be preferable, including the Text 999 copy you put in from Jen. If there is a brief description of the resource by the link that would be great i.e. for situations where you may need to text rather than call 999 - Link to Register with 999

**Comment by Nicky-Cummings** [comment]
Oh also, Jen said ok to remove the refuge safety resource at this stage..

**Comment by bradreeder** [comment]
Great, many thanks for your feedback! Do let me know if anything comes up or springs to mind.

**Comment by bradreeder** [comment]
Jen sent me the following (just so I can read this in one space):

"Hi Bradley,

I've had a look and this looks good!

The safety planning documents I sent you are very long winded, I'm not sure about putting them on as an attachment, I'm happy to look at them tomorrow and see if I can make them more user friendly/ creative. 

Thanks, Jen"

**Comment by Nicky-Cummings** [comment]
Fab! Where are the safety docs attached in github? Can't remember but I could take a look at them too.

**Comment by bradreeder** [comment]
Hi Nicky, I've just uploaded them onto google docs and put them under 'resources' in the wiki. Its possible it'll ask for me to give you permission to view them, so I'll email you a copy.

**Comment by Nicky-Cummings** [comment]
Ok so yes I am familiar with the content on the Safety info doc. How about we just separate tall he info out i.e. have link for the following:

- Making a safety plan
- Preparing to leave
- What to pack if you're planning to leave your partner
- Protecting yourself after you have left
- Register to be able to text 999
