### ISSUE TITLE
should users have the chance to ammend their answers? if so some graphic work is needed to show a selected answer

### ISSUE THREAD

**Issue by daymos** [saferTogether/saferTogether#39]

**Comment by Nicky-Cummings** [comment]
Morning, Do you mean going back into a sort of saved assessment or skipping back pages to amend content?

**Comment by daymos** [comment]
Hi Nicky, sorry this was an internal question. I figure you have already clarified this with one of our team

**Comment by Nicky-Cummings** [comment]
Good :) still getting used to this, ha!

**Comment by daymos** [comment]
ahah, it takes a bit, but you are doing great!

**Comment by Nicky-Cummings** [comment]
Thank you [😊]


Many Thanks
Regards
Nicky Cummings
Domestic Abuse Support Services Coordinator Lancashire Greater Together
07545 473177
davscoordinator@greatertogether.org.uk

[1449839074592_PastedImage]
________________________________
