### ISSUE TITLE
Comments on survey questions

### ISSUE THREAD

**Issue by bradreeder** [saferTogether/saferTogether#43]
Currently we have all the questions from the RIC. When you select yes or no a comment box appears where the user can provide a more detailed response.

A lot of these questions are hard to comment on without any prompts for specific details, for example ‘are you very frightened?’ or ‘is the abuse happening more often?’

Is it necessary that they should be able to provide a comment on every question, or should we only include them on questions that prompt for more details, like ‘is there any other person who has threatened you or who you are afraid of? if yes, please specify whom and why?'

**Comment by Nicky-Cummings** [comment]
Morning Bradley, I understand what you mean however I think we should stick with them just as they are on the RIC. They don't need to complete them if they don't wish to do so but good to have the opportunity to do s should they wish.

**Comment by bradreeder** [comment]
Okay, thanks for letting me know. We will include the option to give a comment after each question.

**Comment by Nicky-Cummings** [comment]
Thanks Bradley.. I just emailed you re plans for the next few days re the app. Please could you let me know how/when the app will be presented for testing and expected next steps/timelines?

**Comment by bradreeder** [comment]
Hi Nicky, I'm just going into a short meeting and then will get back to you immediately.

**Comment by Nicky-Cummings** [comment]
ok great.. Thanks I'm in and out all day but I'll keep checking in..

**Comment by Nicky-Cummings** [comment]
Hi Bradley, do you know when the video will be ready? There are a few of us waiting to check and I could do with nipping out now so would be good to get an update on when we can expect it.. Many thanks, Nicky

**Comment by bradreeder** [comment]
Hi Nicky,

I will be in the office at about 10 30 so I’d expect it some time around 11. Sorry for the delay with this.

Kind regards,

Bradley

**Comment by Nicky-Cummings** [comment]
Great thanks for the update..

**Comment by bradreeder** [comment]
Hi Nicky,

Sorry for the delay the video is uploaded and on github issues now here: https://github.com/saferTogether/saferTogether/issues/63 <https://github.com/saferTogether/saferTogether/issues/63>

We will work on getting a url for the project for you this morning with instructions for viewing it in mobile view.

Regarding next steps Ellie has just told me she will be in touch with you later today, including advice for user research if you decide to go ahead with this build. But if you have any questions or wanted to give any feedback let me know and I’m happy to take a call any time today.

Kind regards,

Bradley
